### ISSUE TITLE
US #3

### ISSUE THREAD

**Issue by NatnaelDanssa** [NatnaelDanssa/capstone-booking-app#3]

**Comment by NatnaelDanssa** [comment]
- [ ] User is able to navigate between the event page and the event form 
- [ ] User is able to navigate with the tab key
- [ ] User is able to enter text
- [ ] User is able to pick a date
- [ ] User is able to submit the form

- [ ] Create a feature branch "feature/navigation"
- [ ] Create an page navigation.js
- [ ] Create a form component ...
- [ ] ... including 2 x Button component to navigate between the event page and the event form 
- [ ] Create an AddEvent Link component
- [ ] Implement logic that routes the user to the event form once the AddEvent link is clicked
- [ ] Implement logic that handles submitting the form data and updating the list of events
- [ ] Implement logic that handles routing the user back to the event overview after submission

**Comment by NatnaelDanssa** [comment]
- [ ] User is able to navigate between the event page and the event form 
- [ ] User is able to navigate with the tab key
- [ ] User is able to enter text
- [ ] User is able to pick a date
- [ ] User is able to submit the form

- [ ] Create a feature branch "feature/navigation"
- [ ] Create an page navigation.js
- [ ] Create a form component ...
- [ ] ... including 2 x Button component to navigate between the event page and the event form 
- [ ] Create an AddEvent Link component
- [ ] Implement logic that routes the user to the event form once the AddEvent link is clicked
- [ ] Implement logic that handles submitting the form data and updating the list of events
- [ ] Implement logic that handles routing the user back to the event overview after submission

**Comment by NatnaelDanssa** [comment]
## Tasks

**Comment by Roland-Hufnagel** [comment]
Hi Natnael, that's a useful feature but here are some points, how to improve your userstory:
- I am confused about your buttons in the wireframe: Does 'Home' lead to the event-list or does 'Events' lead to the event-list? Your AC says: "User is able to navigate between the event page(home) and the event form page". I think to get to the form I have to click the '+'-Button? Please make these details a bit clearer.
- To your second task: I think you should not create a navigation-page but a navigation-component.
- You could define, what inputs the form includes.
- task 4: I think the two buttons should not be part of the form but part of the navigation.
- Last but not least have a look at the formatting of your issue: You may have overwritten the markdown-format for the checkboxes in your tasks (it should be ``[]``, like you did in the acceptance-criterias)

**Comment by FlorianNova** [comment]
lgtm! 👍
